import Navbar,{data} from './components/Navbar'
import Sidebar from './components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import { AppProvider } from './GlobalContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Youtube Clone',
  description: 'Generated by Hrushi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
      <Navbar/>
        {children}
        </AppProvider>
        </body>
    </html>
  )
}
